mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.chatindex, name='index'),
    # path('', views.mongoIndex, name='mongoIndex'),

    path('mongo/', views.mongoIndex, name='mongoIndex'),

    path('<int:question_id>/', views.detail, name='detail'),
    # ex: /polls/5/results/
    path('<int:question_id>/results/', views.results, name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),

    path('chatbot/', views.chatbot, name='chatbot'),


]

polls/models.py
from django.db import models
import datetime
from django.utils import timezone


class Question(models.Model):
    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')


class Choice(models.Model):
    def __str__(self):
        return self.choice_text
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)


class Message(models.Model):
    def __str__(self):
        return self.message_text

    message_text = models.CharField(max_length=200)

polls/views.py
from django.http import HttpResponse, HttpResponseRedirect
from .models import Question, Choice, Message
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from .nlp import chat
import subprocess
from subprocess import Popen, PIPE, STDOUT
from .mongo import parseMango

# def index(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     context = {
#         'latest_question_list': latest_question_list,
#     }
#     return render(request, 'polls/index.html', context)


def index(request):
    # q = chat()
    return HttpResponse("q")


def chatindex(request):
    # question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html')


def mongoIndex(request):
    response = parseMango().mongo_response()
    # response = pm.mongo_response()
    return HttpResponse(response)


global path
path = ""


globvar = ""


def set_globvar_to_one(path):
    global globvar
    globvar = path


def print_globvar():
    print(globvar)


# def chatbot(request):
#     return HttpResponse("q")


def chatbot(request):
    print_globvar()       # Prints 1
    # question = get_object_or_404(Question, pk=question_id)
    input_text = pk = request.POST.get("input", "")
    if(input_text != ""):
        chatObj = chat(input_text)
        isExcecutable = False
        chat_response = chatObj.chat_response()
        print(chat_response[1])

        if(chat_response[1] in {"location", "list", "home"}):
            isExcecutable = True

        if(chat_response[1] in ['home', "application"]):
            set_globvar_to_one(chat_response[0])
            command_response = 'path set to location: '+chat_response[0]
        elif(chat_response[1] in ['goto', 'greeting', 'goodbye', 'thanks']):
            command_response = chat_response[0]
        else:
            command_response = commands(chat_response[0], isExcecutable)
            # set_globvar_to_one(chat_response[0])
        return render(request, 'polls/detail.html', {'message': command_response})
    else:
        return HttpResponse("")


def commands(cmd, isExcecutable):
    print(isExcecutable)
    print(cmd)
    print(globvar)
    print("-----------------------------")
    if(globvar == "" and isExcecutable):
        result = subprocess.getoutput(cmd)
    elif not isExcecutable:
        result = subprocess.getoutput(cmd)
    else:
        print("command to be executed is : "+cmd)
        output = subprocess.Popen(
            cmd, cwd=globvar, stdin=PIPE, stdout=PIPE, stderr=STDOUT)
        result = output.stdout.read().decode("utf-8")
    print("path : " + globvar + " command :" + cmd + "; output : "+result)
    return result


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

polls/templates/polls/detail.html
{% load staticfiles %}
<html>

<head>
    <title>Chatbot</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>
    <div id="searchform" class="main">
        {% if error_message %}
        <p>
            <strong>{{ error_message }}</strong>
        </p>{% endif %}

        <form action="{% url 'polls:chatbot' %}" method="post">
            {% csrf_token %}
            <input id="field" type="text" name="input" id="inputQuery" value="" />
            <input type="submit" value="ask" />
        </form>
        <p>{{message}}</p>
    </div>
</body>

</html>

polls/templates/polls/index.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" /> {% if latest_question_list %}
<ul>
    {% for question in latest_question_list %}
    <li>
        <a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a>
    </li>
    {% endfor %}
</ul>
{% else %}
<p>No polls are available.</p>
{% endif %}

polls/templates/polls/old_detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}
<p>
    <strong>{{ error_message }}</strong>
</p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %} {% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
    <br /> {% endfor %}
    <input type="submit" value="Vote" />
</form>

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
    {% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>